env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
overrides:
  - files: test/*.spec.js
    env:
      mocha: true
rules:
  no-param-reassign:
    - error
    - props: false
